<?php
#error_reporting(E_ALL);
#echo "check";
?>

&Uuml;bersicht der verf&uuml;gbaren ETRON Online Services:

<hr>
<br>
<h2><a href="https://wiki.etron.at/doku.php?id=start" target="_blank">ETRON Wiki</a></h2>
<a href="https://wiki.etron.at/doku.php?id=start" target="_blank"><img src="/static/adminhtml/Etron/Logo/de_DE/Etron_Logo/images/etron_wiki.png" alt="ETRON Wiki preview" /></a>
<br><br>Hier finden Sie Dokumentationen und Anleitungen zu allen Produkten, Services usw.<br><br>
<hr>
<br>
<h2><a href="https://support.etron.at" target="_blank">ETRON webTicket</a></h2>
<a href="https://support.etron.at" target="_blank"><img src="/static/adminhtml/Etron/Logo/de_DE/Etron_Logo/images/etron_web_ticket.png" alt="ETRON webTicket preview" /></a>
<br><br>Hier k&ouml;nnen Fehlermeldungen an uns gesendet werden.<br><br>
<hr>
<br>
<h2><a href="https://www.etron.at/" target="_blank">ETRON Home</a></h2>
<a href="https://www.etron.at/" target="_blank"><img src="/static/adminhtml/Etron/Logo/de_DE/Etron_Logo/images/etron_home.png" alt="ETRON Home preview" /></a>
<br><br>Hier finden Sie Informationen zu Produkten, Kontaktdaten etc.<br><br>
<hr>


