<?php
if($block->Isshowindetailsection()) :?>
<h3><?php echo __('Instagram Feed') ?></h3>
<?php if ($block->showInstagramshoppableImages()) : ?>
<div class="instagramshoppable-view clearer">
	<?php 
	$count = 0;
	foreach ($block->getInstagramshoppableGalleryImages() as $_image):
	$count++; ?>
        <div id="mainimgdiv">
        	<?php 
			$linkurl = "javascript:void(0);";
			$imagetitle = $_image->getImageTitle(); 
			if($_image->getImageLink() != '')
			{
				$linkurl = $_image->getImageLink();
			}
			?>
            <?php if( $_image->getMediaType() == "image"){ ?> 
                    <a href="<?php echo $linkurl; ?>" target="_blank">
                   		 <img src="<?php echo $_image->getThumbnailUrl(); ?>" width="150" height="150" alt="<?php echo $imagetitle; ?>" title="<?php echo $imagetitle; ?>" onmouseover="showinstadesc(<?php echo $count ?>);" onmouseout="hideinstadesc(<?php echo $count ?>);" />
                    </a>
                    <div class="hoverp" id="<?php echo "phover".$count?>" onmouseover="showinstadesc(<?php echo $count ?>);" onmouseout="hideinstadesc(<?php echo $count ?>);">
                   <a href="<?php echo $linkurl; ?>" target="_blank">
                   <div id="innerdiv">
                		<span id="imagelikes"><i class="fa fa-heart" aria-hidden="true"></i><?php echo $_image->getImageLikes()  ?></span>
                    	<span id="imagecomments"><i class="fa fa-comment" aria-hidden="true"></i><?php echo $_image->getImageComments() ?></span>
                	</div>
                    </a>
                </div>
            <?php } else { ?>
	             <video width="100%" height='100%' controls onmouseover="showinstadesc(<?php echo $count ?>);" onmouseout="hideinstadesc(<?php echo $count ?>);">
                	<source src="<?php echo $_image->getThumbnailUrl(); ?>" type="video/mp4">
                	Your browser does not support the video tag.
                </video>
                <div class="hoverp" id="<?php echo "phover".$count?>" onmouseover="showinstadesc(<?php echo $count ?>);" onmouseout="hideinstadesc(<?php echo $count ?>);">
                   <a href="<?php echo $linkurl; ?>" target="_blank">
                   <div id="innerdiv">
                		<span id="imagelikes"><i class="fa fa-heart" aria-hidden="true"></i><?php echo $_image->getImageLikes()  ?></span>
                    	<span id="imagecomments"><i class="fa fa-comment" aria-hidden="true"></i><?php echo $_image->getImageComments() ?></span>
                	</div>
                   </a> 
                </div>
            <?php } ?>
        </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
<script type="text/javascript">
function showinstadesc(Id)
{
	document.getElementById("phover"+Id).className = "hoverp instagramshoppableshow";
}
function hideinstadesc(Id)
{
	document.getElementById("phover"+Id).className = "hoverp";
}
</script>
<?php endif; ?>
