<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<p class="col-m-6"><a href="http://www.etron.at" target="_blank" ><img class="logo-footer" style="float: left !important;" src="<?php $block->getBaseUrl(); ?>/static/adminhtml/Etron/Logo/de_DE/Etron_Logo/images/etron_logo_sm.png" alt="ETRON Home" /></a>
<span style="display: inline-block; padding: 10px;">&copy; <?= date('Y')?> ETRON Administrations - Panel </span></p>